# =============================================================================
# cmake/Prefetch.cmake — download every pinned dependency ahead of time
# =============================================================================
# Usage (script mode, no project needed):
#
#   cmake -DDEST=/opt/starmap-deps -P cmake/Prefetch.cmake
#
# Result:
#   /opt/starmap-deps/<name>/            extracted, hash-verified sources
#   /opt/starmap-deps/prefetched.cmake   an "initial cache" file for `cmake -C`
#
# The Dockerfile runs this once while building the image. Every later
# configure inside the container starts with
#
#   cmake -C /opt/starmap-deps/prefetched.cmake -S /src -B /build ...
#
# and `-C` pre-loads cache entries BEFORE the project's CMakeLists runs, so
# each FetchContent_Declare(<name> ...) finds FETCHCONTENT_SOURCE_DIR_<NAME>
# already set and uses that directory instead of downloading. That's the
# documented override (FetchContent docs, "FETCHCONTENT_SOURCE_DIR_<uppercaseName>").
#
# WHY PREFETCH AT ALL?
#   * Offline, reproducible container builds: the image carries the exact
#     archives the hashes vouch for; a GitHub outage or a CI box without
#     internet doesn't break the build (the build even works with
#     `docker run --network none`).
#   * Speed: SDL3 + bgfx.cmake are ~100 MB to download and extract. Doing it
#     once per image, not once per fresh build directory, saves that each time.
#   * Sharing: many build directories (Release, Debug, ...) reuse one
#     read-only copy. Only the per-build outputs (<name>-build dirs) go into
#     the build tree.
#
# WHY FetchContent_Populate AND NOT file(DOWNLOAD) + file(ARCHIVE_EXTRACT)?
#   FetchContent_Populate(<name> URL ... URL_HASH ...) is the exact code path
#   a normal configure uses, so the result is byte-for-byte what a normal
#   build would have downloaded: hash check, the "strip the single top-level
#   directory" rule for archives, the same extraction. Re-implementing that
#   by hand invites subtle differences (e.g. the SQLite zip nests its files in
#   sqlite-amalgamation-3530400/, which FetchContent strips).
#   This "direct" form of FetchContent_Populate (with content options) is
#   allowed in script mode and is NOT the deprecated single-argument form
#   that CMake 3.30's policy CMP0169 warns about.
# =============================================================================
cmake_minimum_required(VERSION 3.24)

if(NOT DEFINED DEST)
    message(FATAL_ERROR "Usage: cmake -DDEST=<dir> -P ${CMAKE_CURRENT_LIST_FILE}")
endif()

include(FetchContent)
include(${CMAKE_CURRENT_LIST_DIR}/DependencyPins.cmake)

# Scratch space for FetchContent's helper sub-build (CMake < 3.30 drives the
# download through a tiny generated ExternalProject; 3.30+ does it directly).
# It must NOT end up in the image, so it lives outside DEST.
set(_scratch "${DEST}-scratch")

set(_cache_lines
    "# Generated by cmake/Prefetch.cmake. Load with: cmake -C <this file> ...\n"
    "# Each entry makes FetchContent use a pre-downloaded source directory\n"
    "# instead of downloading (see cmake/DependencyPins.cmake).\n")

foreach(_name IN LISTS STARMAP_PINNED_DEPS)
    set(_src "${DEST}/${_name}")
    message(STATUS "Prefetching ${_name} -> ${_src}")
    FetchContent_Populate(${_name}
        URL        ${STARMAP_PIN_${_name}_URL}
        URL_HASH   ${STARMAP_PIN_${_name}_HASH}
        DOWNLOAD_EXTRACT_TIMESTAMP TRUE
        SOURCE_DIR   "${_src}"
        SUBBUILD_DIR "${_scratch}/${_name}-subbuild"
        BINARY_DIR   "${_scratch}/${_name}-build")
    # FetchContent upper-cases the declared name for its override variable:
    # SDL3 -> FETCHCONTENT_SOURCE_DIR_SDL3, sqlite_amalgamation ->
    # FETCHCONTENT_SOURCE_DIR_SQLITE_AMALGAMATION.
    string(TOUPPER "${_name}" _upper)
    list(APPEND _cache_lines
        "set(FETCHCONTENT_SOURCE_DIR_${_upper} \"${_src}\" CACHE PATH \"prefetched ${_name}\")\n")
endforeach()

file(WRITE "${DEST}/prefetched.cmake" ${_cache_lines})
file(REMOVE_RECURSE "${_scratch}")
message(STATUS "Wrote ${DEST}/prefetched.cmake")
